package com.vibro.care.Config;

public class Config {
    //public static String MainURL = "http://xfacttech.com/vibro/";
    //public static String MainURL = "http://192.168.161.193/vibro/";
    public static final String MainURL = "http://vibrostudy.in/backend/";
    public static final String AppURL = MainURL + "app/";
    public static final String RegistrationURL = AppURL + "register.php";
    public static final String LoginURL = AppURL + "login.php";
    public static final String LogoutURL = AppURL + "logout.php";
    public static final String ForgetURL = AppURL + "forget.php";
    public static final String CheckURL = AppURL + "check_login.php";
    public static final String SupportURL = AppURL + "support.php";
    public static final String CreateURL = AppURL + "create.php";
    public static final String DataURL = AppURL + "data.php";
    public static final String UpdateURL = AppURL + "update.php";
    public static final String DetailsURL = AppURL + "details.php";
    public static final String TransactionURL = AppURL + "transaction.php";
    public static final String UserDetailsURL = AppURL + "user_details.php";
    public static final String FeedbackURL = AppURL + "feedback.php";

    public static final String id = "id";
    public static final String name = "name";
    public static final String person = "cont_name";
    public static final String email = "email";
    public static final String phone = "phone";
    public static final String gender = "gender";
    public static final String address = "address";
    public static final String website = "website";
    public static final String GST = "GST";
    public static final String PAN = "PAN";
    public static final String date = "date_inc";
    public static final String AADHAR = "AADHAR";
    public static final String country = "country";
    public static final String state = "state";
    public static final String city = "city";
    public static final String PIN = "PIN";
    public static final String business = "business_type";
    public static final String service = "service_details";
    public static final String experience = "experience";
    public static final String instruments = "instruments";
    public static final String projects = "projects";
    public static final String company_type = "company_type";
    public static final String size = "size";
    public static final String category = "category";
    public static final String type = "type";
    public static final String device_id = "device_id";
    public static final String image = "image";
    public static final String accessid = "accessid";
    public static final String razorpay = "razorpay";
    public static final String login = "login";
    public static final String password = "password";
    public static final String user_data = "user_data";
    public static final String table = "table";
    public static final String message = "message";
    public static final String data = "data";
    public static final String status = "status";
}